#!/bin/sh

mkdir -p /newroot
mount -t tmpfs tmpfs /newroot
if [ -e /tmp/backup_flash.tar.gz ]; then
	mv /tmp/backup_flash.tar.gz /newroot/
fi
cp /bin/ofgwrite_bin /newroot/
/newroot/ofgwrite_bin "$@"
